#! /bin/sh

# $Id$

# ---------------------------------------------------
# PEAR DB TEST STARTER
#
#   To run all tests:  ./run
#   To run one test:   ./run <test name>.phpt
#   Example:           ./run db_parsedsn.phpt
#
#   Before running the tests you must adjust three
#   settings:
#     1)  the TEST_PHP_EXECUTABLE environment variable
#     2)  the full path/name of your run-tests.php file
#     3)  the full path to the current directory

# ---------------------------------------------------
# Set the environment variable
#
#   This variable must contain the full path and
#   file name of your PHP CLI executable.
#
#   For csh style shells:
#   ---------------------
# setenv TEST_PHP_EXECUTABLE c:/progra~1/php/php.exe
#
#   For sh style shells:
#   --------------------
TEST_PHP_EXECUTABLE=c:/progra~1/php/php.exe
export TEST_PHP_EXECUTABLE


# ---------------------------------------------------
# Change the paths as needed
#
# Sample Format:
#   VAR <full path to>/run-tests.php <full path to current dir>/$1

$TEST_PHP_EXECUTABLE c:/progra~1/php/run-tests.php d:/dbtests/tests/$1
